apiVersion: v1
kind: Service
metadata:
  name: configmapservice
spec:
  selector:
    name: configmapdeployment
  ports:
    - port: 8080
      nodePort: 32154
      targetPort: 8080
      protocol: TCP
  type: NodePort